name: dma-authorization-server
services:
    dma-as:
        image: dnd-mapp/dma-as:latest
        container_name: dma-authentication-server
        restart: on-failure
        env_file:
            - .env
        ports:
            - '3000:3000/tcp'
    dbeaver:
        image: dbeaver/cloudbeaver:latest
        container_name: dbeaver
        restart: unless-stopped
        depends_on:
            - mariadb-server
        ports:
            - '8978:8978'
        volumes:
            - ./dbeaver-workspace:/opt/cloudbeaver/workspace
        extra_hosts:
            - 'mariadb-server:127.0.0.1'
    mariadb-server:
        image: mariadb:latest
        container_name: mariadb-server
        ports:
            - '3306:3306'
        volumes:
            - ./mariadb/data:/var/lib/mysql
            - ./start.sh:/docker-entrypoint-initdb.d/start.sh
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
        secrets:
            - mariadb-root-password
            - mariadb-user-password
secrets:
    mariadb-root-password:
        file: ./mariadb/root-password.txt
    mariadb-user-password:
        file: ./mariadb/user-password.txt
