name: Build
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
env:
    COOKIE_SIGNING_SECRET: ${{ secrets.COOKIE_SIGNING_SECRET }}
jobs:
    execute:
        name: Execute
        uses: dnd-mapp/actions/.github/workflows/build.yml@main
        with:
            COOKIE_SIGNING_SECRET: ${{ env.COOKIE_SIGNING_SECRET }}
